### ISSUE TITLE
If you upgrade Docker on a Mac - you may get some odd issues with the docker-compose up

### ISSUE THREAD

**Issue by JGFMK** [spurin/diveintoansible-lab#10]
Here were my initial results:

```

docker-compose up

Creating network "diveinto.io" with the default driver
Pulling ubuntu-c (spurin/diveintoansible:ansible)...
Traceback (most recent call last):
  File "site-packages/docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "site-packages/docker/credentials/store.py", line 35, in get
  File "site-packages/docker/credentials/store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 356, in ensure_image_exists
  File "compose/service.py", line 1267, in pull
  File "compose/progress_stream.py", line 99, in get_digest_from_pull
  File "compose/service.py", line 1234, in _do_pull
  File "site-packages/docker/api/image.py", line 396, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 324, in resolve_authconfig
  File "site-packages/docker/auth.py", line 235, in resolve_authconfig
  File "site-packages/docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop exited with "No stored credential for https://index.docker.io/v1/".')
[96158] Failed to execute script docker-compose
```

I upgraded Docker Desktop to this build
<img width="759" alt="Screenshot 2021-01-13 at 14 51 37" src="https://user-images.githubusercontent.com/14791808/104468240-20088880-55af-11eb-91bb-a8138fba3249.png">

 I read about things in this related post
https://github.com/shin-/dockerpy-creds/issues/13

And similar stuff here
https://github.com/docker/for-mac/issues/3785

Initially my  *~/.docker/config.json* looked like this:

<img width="532" alt="Screenshot 2021-01-13 at 13 20 42" src="https://user-images.githubusercontent.com/14791808/104470782-ff8dfd80-55b1-11eb-95c4-c5a6c599da9a.png">

I tried running docker logout and docker login, thinking there were some caching issues.
When I tried to login again initially I got some bizarre exception:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x46742b4]
```
so I renamed  *~/.docker/config.json* to  *~/.docker/config.json-old* 

Then I got prompted for 

It now forces you to have a docker-hub password.
Now I was prompted with:
Login with your Docker ID to push and password.

So I headed over to https://hub.docker.com/ and signed up. It appears there's a free subscription for pull requests:

When I reran *docker-compose up* this time everything worked fine.
I'll also note, a *~/.docker/config.json*  was recreated with the following content

<img width="623" alt="Screenshot 2021-01-13 at 15 07 54" src="https://user-images.githubusercontent.com/14791808/104470823-0b79bf80-55b2-11eb-86ec-4d46d8f5a35f.png">

You will notice the auths and credsStore key/value pairs look quite different now!

Hope this helps anyone else caught in the Mac/Docker upgrade (I was on Mojave 10.14.6 - and all the Docker App Contents and usr/local/bin symlinks were fine (you may see this in other posts)

**Comment by spurin** [comment]
This is brilliant!  Thanks so much Jeremy @JGFMK 

Hope this helps others, who may encounter the same issue.
