### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by latifbilbao** [spurin/diveintoansible-lab#77]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2595] Failed to execute script docker-compose
abdouls-macbook-pro:diveintoansible-lab abdoullatifdiallo$

**Comment by spurin** [comment]
Hi @latifbilbao 

This error is super annoying as it looks very simple but, is actually quite simple.

Docker isn't running.  If you start up Docker you should be good.

Would be great if docker-compose had a friendlier exception message but alas, this is it at the moment (might be a good project for someone to fix 😁).

Let me know how you get on please.

Thanks


James

**Comment by latifbilbao** [comment]
uring handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[2746] Failed to execute script docker-compose
abdouls-macbook-pro:diveintoansible-lab abdoullatifdiallo$

**Comment by latifbilbao** [comment]
exit
abdouls-macbook-pro:~ abdoullatifdiallo$ docker run -it --rm ubuntu bash
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
abdouls-macbook-pro:~ abdoullatifdiallo$

**Comment by spurin** [comment]
Hi @latifbilbao 

Did you see my earlier message?  Docker doesn't appear to be running on your system based on the output, from the docker-compose and the docker cli command that you executed.

**Comment by latifbilbao** [comment]
Starting docker    ... done
Starting ubuntu3   ... done
Starting ubuntu-c  ... done
Starting ubuntu1   ... done
Starting centos3   ... done
Recreating centos1 ... done
Starting ubuntu2   ... done
Starting centos2   ... done
Recreating portal  ... done
Attaching to docker, ubuntu3, ubuntu-c, ubuntu1, centos3, centos2, ubuntu2, centos1, portal

**Comment by latifbilbao** [comment]
Thank you

**Comment by spurin** [comment]
Brilliant, glad it's resolved @latifbilbao 

Enjoy the rest of the course!
